# Generated by Django 6.0.6 on 2026-06-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('idle_time_hours', models.FloatField()),
                ('wasted_cost_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
