# Generated by Django 6.0.6 on 2026-06-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpuTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('gpu_id', models.IntegerField(default=0)),
                ('temperature_celsius', models.FloatField()),
                ('vram_usage_mb', models.FloatField()),
                ('vram_total_mb', models.FloatField(default=80000)),
                ('gpu_utilization_percent', models.FloatField()),
                ('power_draw_watts', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
