# Generated by Django 6.0.6 on 2026-06-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gputelemetry',
            name='node_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='gputelemetry',
            index=models.Index(fields=['node_id', 'timestamp'], name='telemetry_g_node_id_efd127_idx'),
        ),
    ]
