# Generated by Django 6.0.6 on 2026-07-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('llm_inference', 'LLM Inference'), ('image_processing', 'Image Processing'), ('data_pipeline', 'Data Pipeline'), ('model_training', 'Model Training'), ('vector_search', 'Vector Search'), ('code_execution', 'Code Execution')], max_length=32)),
                ('file_input_size_gb', models.FloatField(default=1.0)),
                ('image_count', models.IntegerField(default=0)),
                ('thinking_depth', models.IntegerField(default=1)),
                ('complexity_factor', models.FloatField(default=1.0)),
                ('selected_tier', models.IntegerField()),
                ('allocated_nodes', models.IntegerField()),
                ('required_nodes', models.IntegerField()),
                ('efficiency_pct', models.FloatField(default=0.0)),
                ('verdict', models.CharField(blank=True, choices=[('optimal', 'Optimal'), ('overload', 'Overload'), ('idle_waste', 'Idle Waste')], max_length=16)),
                ('status', models.CharField(choices=[('analyzing', 'Being Analyzed'), ('processing', 'In Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='analyzing', max_length=16)),
                ('bottleneck_analysis', models.TextField(blank=True)),
                ('recommendations', models.JSONField(default=list)),
                ('demo_talking_points', models.JSONField(default=list)),
                ('ai_raw_report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
