# Generated by Django 6.0.6 on 2026-07-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='allocated_nodes_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='chat_session_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='response_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='task_type',
            field=models.CharField(choices=[('ocr_data_retrieval', 'OCR & Data Retrieval'), ('image_generation', 'Image Generation'), ('batch_vision', 'Batch Vision Processing'), ('image_editing', 'Image Editing'), ('large_ml_project', 'Large ML Project')], max_length=32),
        ),
    ]
