# Generated by Django 6.0.6 on 2026-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_simulationrun_allocated_nodes_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='user_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='task_type',
            field=models.CharField(choices=[('ocr_data_retrieval', 'OCR & Data Retrieval'), ('image_generation', 'Image Generation'), ('batch_vision', 'Batch Vision Processing'), ('image_editing', 'Image Editing'), ('large_ml_project', 'Large ML Project'), ('video_generation', 'Video Generation'), ('code_edit', 'Code Editing'), ('production_saas', 'Production SaaS Workload'), ('normal_chats', 'Normal Chats')], max_length=32),
        ),
    ]
