# Generated by Django 6.0.6 on 2026-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_simulationrun_user_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='company_name',
            field=models.CharField(blank=True, default='Default AI Co', max_length=255),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Normal', 'Normal'), ('Background', 'Background')], default='Normal', max_length=50),
        ),
    ]
