# Generated by Django 6.0.6 on 2026-07-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_simulationrun_company_name_simulationrun_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('goal_cost', models.BooleanField(default=False)),
                ('goal_latency', models.BooleanField(default=False)),
                ('goal_balanced', models.BooleanField(default=True)),
                ('goal_throughput', models.BooleanField(default=False)),
                ('initial_gpu_count', models.IntegerField(default=128)),
                ('cpu_nodes', models.IntegerField(default=64)),
                ('budget', models.IntegerField(default=500000)),
                ('services', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
