# Generated by Django 6.0.6 on 2026-06-26 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['target_resource', 'requested_at'], name='gate_approv_target__0f498a_idx'),
        ),
    ]
